Repository crayon/terraform-azurerm-aks, pull requests merged in 2021-09, with the labels that each got.

#12 Changelog and release-drafter work
  .github/release-drafter.yml
  CHANGELOG.md
Labels: enhancement

#13 New workflow
  .github/workflows/automation.yml
  CHANGELOG.md
  aks.tf
  variables.tf
Labels: Type: Feature

#17 Add node_resource_group and fix bug with dns_prefix
  CHANGELOG.md
  aks.tf
  locals.tf
  variables.tf
Labels: Type: Enhancement

#19 Added Azure RBAC to close #15
  CHANGELOG.md
  aks.tf
  variables.tf
Labels: Type: Feature

#20 Update providers, fixes #18
  main.tf
Labels: Type: Enhancement

#21 Add the kubelet_identity property to module outputs
  outputs.tf
Labels: Type: Feature, Status: Accepted
